# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(7, 7)
print(tensor_A)
print(tensor_A.shape)

tensor([[0.8676, 0.5587, 0.1762, 0.1908, 0.7712, 0.7215, 0.7156],
        [0.3788, 0.3773, 0.2012, 0.4778, 0.2649, 0.6360, 0.1532],
        [0.5069, 0.3365, 0.0400, 0.2325, 0.7220, 0.3378, 0.9688],
        [0.3234, 0.5784, 0.0848, 0.2343, 0.5020, 0.6488, 0.7942],
        [0.9887, 0.0982, 0.0725, 0.6123, 0.6911, 0.7368, 0.8476],
        [0.2814, 0.7688, 0.6489, 0.6299, 0.5842, 0.1036, 0.2043],
        [0.2004, 0.8547, 0.1287, 0.1400, 0.8711, 0.4850, 0.6092]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)

# Perform matrix multiplication
tensor_C = torch.matmul(tensor_A, tensor_B.T)
print(tensor_C)
print(tensor_C.shape)

tensor([[1.6068],
        [1.0337],
        [1.4582],
        [1.4298],
        [1.8329],
        [1.2812],
        [1.3332]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_D = torch.rand(7, 7)
tensor_E = torch.rand(1, 7)

# Matrix multiply tensors
tensor_F = torch.matmul(tensor_D, tensor_E.T)
print(f"({tensor_F},\n {tensor_F.shape})")

(tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]),
 torch.Size([7, 1]))


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_G = torch.rand(2, 3).to(device)
tensor_H = torch.rand(2, 3).to(device)
print(f"({tensor_G},\n {tensor_H})")

Device: cpu
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]]))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_G and tensor_H
# Shapes are (2, 3) and (2, 3), so we need to transpose H
tensor_I = torch.matmul(tensor_G, tensor_H.T)
print(f"({tensor_I}, {tensor_I.shape})")


(tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]), torch.Size([2, 2]))


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
max_val = tensor_I.max()
print(f"Max: {max_val}")

# Find min
min_val = tensor_I.min()
print(f"Min: {min_val}")

Max: 0.5617256760597229
Min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max 
argmax_val = tensor_I.argmax()
print(f"Argmax: {argmax_val}")

# Find arg min 
argmin_val = tensor_I.argmin()
print(f"Argmin: {argmin_val}")

Argmax: 3
Argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_J = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_K = tensor_J.squeeze()

# Print out tensors and their shapes
print(tensor_J, tensor_J.shape)
print(tensor_K, tensor_K.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
